// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEH1rMix-iFYsYX1NIgIyxBO0g-HDeCBk',
    appId: '1:526928917348:android:d23c8df973dcde47320071',
    messagingSenderId: '526928917348',
    projectId: 'fitnessapp-cb7f1',
    storageBucket: 'fitnessapp-cb7f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2rk1WRdxZvwap1MrDlRRETbJpBxd4-78',
    appId: '1:526928917348:ios:cb38f6134e91f1d5320071',
    messagingSenderId: '526928917348',
    projectId: 'fitnessapp-cb7f1',
    storageBucket: 'fitnessapp-cb7f1.firebasestorage.app',
    iosBundleId: 'com.example.appfitclientes',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzX8TKYHoXc1x1AmrdA1tJLO5XuM_amJM',
    appId: '1:526928917348:web:f57e5dc743bcaa50320071',
    messagingSenderId: '526928917348',
    projectId: 'fitnessapp-cb7f1',
    authDomain: 'fitnessapp-cb7f1.firebaseapp.com',
    storageBucket: 'fitnessapp-cb7f1.firebasestorage.app',
    measurementId: 'G-CVYD8TVW1R',
  );

}